authentication/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path

from authentication import views

app_name = 'authentication'

urlpatterns = [
    path('', views.CustomLoginView.as_view(), name='login'),
    path('admin/login/', views.CustomLoginView.as_view(), name='admin_login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profil/', views.profil, name='profil'),
]

gestion_appointement/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    path('', include('authentication.urls')),
    path('dashboard/', include('personnel.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personnel/urls.py
from django.urls import path, include

from personnel import views

app_name = 'personnel'

urlpatterns = [
    path('', views.remuneration, name='remuneration'),
    path('create/fiche', views.fichedepaie_add, name='fichedepaie_add'),
    path('modifier/fiche/<int:fiche_id>/', views.modifier_fichedepaie, name='modifier_fichedepaie'),
    path('affiche/fiche/<int:fiche_id>/', views.fichedepaie_detail, name='fichedepaie_detail'),
    path('print/<int:fiche_id>/', views.print_fichedepaie, name='print_fichedepaie'),
    path('demande-credit/', views.demande_credit, name='demande_credit'),
    path('traiter-demande-credit/', views.traiter_demande_credit, name='traiter_demande_credit'),
    path('approuver-credit/<int:id>/', views.approuver_credit, name='approuver_credit'),
    path('rejeter-credit/<int:id>/', views.rejeter_credit, name='rejeter_credit'),
    path('voir-detail-credit/<int:id>/', views.voir_detail_credit, name='voir_detail_credit'),
    path('presence', views.presence, name='presence'),
    path('notifier/heures/', views.heures_supplementaires, name='heure_supplementaire'),
    path('edit/<int:heure_id>/', views.edit_overtime, name='edit_overtime'),
    path('delete/<int:heure_id>/', views.delete_overtime, name='delete_overtime'),
    path('rapport/presences/', views.rapport_presences, name='rapport_presences'),
    path('rapport/imprimer/<int:agent_id>/', views.imprimer_rapport, name='imprimer_rapport'),
]

authentication/models.py
from django.contrib.auth.models import AbstractUser, Group
from django.core.validators import RegexValidator
from django.db import models

from django.contrib.auth.models import AbstractUser, Group
from django.core.validators import RegexValidator
from django.db import models


class Utilisateur(AbstractUser):
    MANAGER = 'Manager'
    ADMINISTRATEUR_IT = 'Administrateur IT'
    GESTIONNAIRE_PAIE = 'Gestionnaire Paie'
    AGENT = 'Agent'

    ROLE_CHOICES = (
        (MANAGER, 'Manager'),
        (ADMINISTRATEUR_IT, 'Administrateur IT'),
        (GESTIONNAIRE_PAIE, 'Gestionnaire Paie'),
        (AGENT, 'Agent'),
    )

    # Ajout des champs supplémentaires
    profile_photo = models.ImageField(verbose_name='Photo de profil', upload_to='profile_photos/', null=True,
                                      blank=True)
    genre = models.CharField(max_length=10, choices=[('M', 'Masculin'), ('F', 'Féminin')])
    telephone = models.CharField(max_length=15, validators=[
        RegexValidator(
            regex=r'^\+?1?\d{9,15}$',
            message="Le numéro de téléphone doit être entré au format: '+999999999'. Jusqu'à 15 chiffres autorisés."
        )
    ])
    role = models.CharField(max_length=30, choices=ROLE_CHOICES, verbose_name='Rôle')

    # Ajout du numéro RFID de l'agent
    rfid_number = models.CharField(max_length=50, verbose_name='Numéro RFID', unique=True, null=True, blank=True)
    matricule = models.CharField(max_length=50, verbose_name='Matricule', unique=True, null=True, blank=True)

    # Attributs supplémentaires pour l'agent
    poste = models.CharField(max_length=100, verbose_name='Poste', null=True, blank=True)
    departement = models.CharField(max_length=100, verbose_name='Département', null=True, blank=True)
    date_entree = models.DateField(verbose_name="Date d'entrée", null=True, blank=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        # Gestion des groupes en fonction du rôle de l'utilisateur
        if self.role == self.MANAGER:
            group, _ = Group.objects.get_or_create(name='Manager')
            group.user_set.add(self)
        elif self.role == self.ADMINISTRATEUR_IT:
            group, _ = Group.objects.get_or_create(name='Administrateur IT')
            group.user_set.add(self)
        elif self.role == self.GESTIONNAIRE_PAIE:
            group, _ = Group.objects.get_or_create(name='Gestionnaire Paie')
            group.user_set.add(self)
        elif self.role == self.AGENT:
            group, _ = Group.objects.get_or_create(name='Agent')
            group.user_set.add(self)

    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.username})"

authentication/forms.py
from django import forms
from .models import Utilisateur


class ProfilForm(forms.ModelForm):
    class Meta:
        model = Utilisateur
        fields = ['first_name', 'last_name', 'email', 'telephone', 'genre', 'profile_photo']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nom'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Prénom'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'telephone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Téléphone'}),
            'genre': forms.Select(choices=[('M', 'Masculin'), ('F', 'Féminin')], attrs={'class': 'form-control'}),
            'profile_photo': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
        }

authentication/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.contrib import messages
from django.shortcuts import render, reverse, redirect

from authentication.forms import ProfilForm


class CustomLoginView(LoginView):
    template_name = 'authentication/login.html'
    redirect_authenticated_user = True

    def get_success_url(self):
        user = self.request.user
        if user.is_superuser:
            return reverse('admin:index')
        elif user.role == 'Manager':
            return reverse('personnel:traiter_demande_credit')
        elif user.role == 'Administrateur IT':
            return reverse('admin:index')
        elif user.role == 'Gestionnaire Paie':
            return reverse('personnel:remuneration')
        elif user.role == 'Agent':
            return reverse('personnel:presence')
        return super().get_success_url()


@login_required
def profil(request):
    user = request.user  # Récupérer l'utilisateur connecté
    context = {
        'user': user  # Passez l'utilisateur au contexte
    }
    return render(request, 'authentication/profil.html', context)

authentication/templates/authentication/login.html
<!DOCTYPE html>
{% load static %}
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href={% static "personnel/assets/images/logo.png" %} rel="icon">
    <title>Se connecter</title>
</head>
<body>
<div class="wrapper">
    <img src="{% static 'personnel/assets/images/logo.png' %}" alt="Logo" width="50px" height="50px">
    <h1>S'authentifier</h1>
    <form action="{% url 'authentication:login' %}" method="POST">
        {% csrf_token %}
        <div class="input-box">
            <input type="text" placeholder="Nom d'utilisateur" required name="username">
        </div>
        <div class="input-box">
            <input type="password" placeholder="Votre mot de passe" required name="password">
        </div>
        {% if form.errors %}
            <div class="alert alert-danger">
                {% for field in form %}
                    {% for error in field.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
        {% endif %}
        <div class="input-box button">
            <input type="Submit" value="Se connecter">
        </div>
    </form>
</div>
</body>

<style>
    @import url('https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap');

    :root {
        --primary: #1ba1db;
    }

    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        font-family: 'Poppins', sans-serif;
    }

    body {
        min-height: 100vh;
        display: flex;
        align-items: center;
        justify-content: center;
        background: var(--primary);
    }

    .wrapper {
        position: relative;
        max-width: 430px;
        width: 100%;
        background: #fff;
        padding: 34px;
        border-radius: 6px;
        box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
        margin: 20px;
    }

    .wrapper h1 {
        position: relative;
        font-size: 22px;
        font-weight: 600;
        color: #333;
        text-align: center;
    }

    .wrapper h1::before {
        content: '';
        position: absolute;
        left: 10;
        bottom: 0;
        height: 3px;
        width: 40px;
        border-radius: 12px;
        background: var(--primary)

    }

    .wrapper form {
        margin-top: 30px;
    }

    .wrapper form .input-box {
        height: 52px;
        margin: 18px 0;
    }

    form .input-box input {
        height: 100%;
        width: 100%;
        outline: none;
        padding: 0 15px;
        font-size: 17px;
        font-weight: 400;
        color: #333;
        border: 1.5px solid #C7BEBE;
        border-bottom-width: 2.5px;
        border-radius: 6px;
        transition: all 0.3s ease;
    }

    .input-box input:focus,
    .input-box input:valid {
        border-color: var(--primary);
    }

    form .policy {
        display: flex;
        align-items: center;
    }

    form h3 {
        color: #707070;
        font-size: 14px;
        font-weight: 500;
        margin-left: 10px;
    }

    .input-box.button input {
        color: #fff;
        letter-spacing: 1px;
        border: none;
        background: var(--primary);
        cursor: pointer;
    }

    .input-box.button input:hover {
        background: rgb(84, 117, 214);
    }

    form .text h3 {
        color: #333;
        width: 100%;
        text-align: center;
    }

    form .text h3 a {
        color: var(--primary);
        text-decoration: none;
    }

    form .text h3 a:hover {
        text-decoration: underline;
    }

    .alert {
        padding: 15px;
        margin-bottom: 20px;
        border: 1px solid transparent;
        border-radius: 4px;
        font-size: 14px;
    }

    .alert-danger {
        color: #a94442;
        background-color: #f2dede;
        border-color: #ebccd1;
    }
</style>
</html>

authentication/templates/authentication/profil.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Profil Utilisateur - Notariat{% endblock title %}
{% block head_h1 %} Profil Utilisateur {% endblock head_h1 %}
{% block lien_head %} <a class="active" href="#">Profil Utilisateur</a> {% endblock %}

{% block content %}
    <div class="main-content">
        <!-- FICHE DE PROFIL -->
        <div class="profile-container">
            <h3>Informations du Profil</h3>
            <div class="profile-header">
                <img src="{% if user.profile_photo %}{{ user.profile_photo.url }}{% else %}{% static 'personnel/assets/images/profil_defaut.png' %}{% endif %}" alt="Photo de Profil"
                     class="profile-pic">
                <div class="profile-info">
                    <h4>{{ user.get_full_name }}</h4> <!-- Affiche le nom complet de l'utilisateur -->
                    <p>{{ user.role }}</p> <!-- Affiche le rôle de l'utilisateur -->
                    <p>Matricule : {{ user.matricule|default_if_none:'Aucun' }}</p>
                </div>
            </div>
            <table class="profile-details">
                <thead>
                <tr>
                    <th colspan="2">Détails du Profil</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>Email:</td>
                    <td>{{ user.email }}</td>
                </tr>
                <tr>
                    <td>Téléphone:</td>
                    <td>{{ user.telephone }}</td>
                </tr>
                <tr>
                    <td>Adresse:</td>
                    <td>{{ user.adresse }}</td> <!-- Si vous avez un champ d'adresse dans votre modèle -->
                </tr>
                <tr>
                    <td>Date d'Embauche:</td>
                    <td>{{ user.date_entree|date:"d-m-Y" }}</td> <!-- Formatez la date d'entrée -->
                </tr>
                </tbody>
            </table>
        </div>
        <!-- FICHE DE PROFIL -->
    </div>
{% endblock content %}